name: Swift

on: 
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Start xcodebuild test
      run: xcodebuild clean test -project List.xcodeproj -scheme List -destination "platform=iOS Simulator,name=iPhone 11 Pro"
